version: '3.3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: './api'
    volumes:
      - /app/node_modules
      - ./api:/app
  nginx:
    depends_on:
      - api
      - ui
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "81:80"
  ui:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./ui
    volumes:
      - /app/node_modules
      - ./ui:/app
    environment:
      - PRODUCTION=true

